version: '3'

services:
  tappay-test:
    image: node:20
    # 設定開發容器名稱
    container_name: tappay-test
    restart: "no"
    # 指定工作目錄
    working_dir: /root/tappay-test
    volumes:
      # 掛載根目錄下資料夾到容器中
      - ../:/root/tappay-test
    # 安裝 pm2 及 持久化容器
    command: sh -c "tail -f /dev/null"